<?php

/*
### stream.php
Displays a stream of badge statements including the badge image and signed statement verification. 
*/

/*
TODO: I had to remove JQuery UI from the viewer as it didn't work with bootstrap; I now need to make the statement 
collpase work again and generally make the page look nicer.

TODO: display images attached to statements

TODO: display an icon indicating whether or not the statement has been signed and if the signature has been verified. 

*/
?>

<h3>Badge Stream</h3>
<p>
    All statements about Open Badges for all users are shown below. 
</p><p>
    Statements generated by this prototype are signed and those
    signatures are verified in the stream below. This prototype leaves it up to the end user to confirm that the signature 
    is hosted at the url controlled by a trusted authority (this url is shown in <span class='label label-default'>grey</span>). 
    A real system could handle this for the user by using a whitelist of trusted certifcate locations, either 
    stored within the system itself or provided by a trusted 3rd party. 
</p>

<script src="TinCanStatementViewer/scripts/jquery-1.6.3.min.js"></script>
<script src="TinCanStatementViewer/scripts/base64.js"></script>
<script src="TinCanJS/build/tincan-min.js"></script>
<script src="TinCanStatementViewer/scripts/TinCanQueryUtils.js"></script>
<script src="TinCanStatementViewer/scripts/TinCanViewer.js"></script>
<script src="TinCanViewerOverrides.js"></script>

<div id="searchBox" style="display: none;">
    <input type="hidden" id="version" value="<?php echo $CFG->version ?>" />
    <input type="hidden" id="agentProperty" value="mbox" />
    <input id="agentValue" type="hidden" value="">
    <input id="verb1" type="hidden" value="">
    <input id="activityId1" type="hidden" value="http://standard.openbadges.org/xapi/recipe/base/0">
    <input id="format" type="hidden" value="canonical">
    <input id="since1" type="hidden" value="">
    <input id="until1" type="hidden" value="">
    <input id="registration1" type="hidden" value="">
    <input id="relatedAgents" type="hidden">
    <input id="relatedActivities" type="checkbox" checked>
    <input id="attachments" type="checkbox" checked>

    <textarea readonly="true" id="TCAPIQueryText"></textarea>

</div>
<div id='theStatements'></div>
<div id='statementsLoading'>
    <img src="TinCanStatementViewer/img/loading.gif" alt="Loading">
</div>
<button id='showAllStatements' class="btn btn-info">More...</button>


<script>
//TODO: but this in a separate js file
    function Config() {
        "use strict";
    }
    Config.endpoint = "<?php echo $CFG->endpoint ?>";
    Config.authUser = "<?php echo $CFG->readonly_login ?>";
    Config.authPassword = "<?php echo $CFG->readonly_pass ?>";
    Config.actor = { "mbox":["<?php echo $userEmail; ?>"], "name":["<?php echo $userName ?>"] };

    $(document).ready(function(){
        TC_VIEWER = new TINCAN.Viewer();
        TC_VIEWER.pageInitialize();
        TC_VIEWER.searchStatements();
        $(".statement").each(function(index){
            console.log("statement");
            displayAttachments($(this));
        });

    });

    function displayAttachments(statementElement){
        var statement = new TinCan.Statement(statementElement.next(".tc_rawdata").children("pre").text());
    }
</script>