<?php
/*
Copyright 2015 Rustici Software

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

### stream.php
Displays a stream of badge statements including the badge image and signed statement verification. 
*/

?>

<h3>Badge Stream</h3>
<p>
    All statements about Open Badges for all users are shown below. 
</p><p>
    Statements generated by this prototype are signed and those
    signatures are verified in the stream below. This prototype leaves it up to the end 
    user to confirm that the signature is hosted at the url controlled by a trusted 
    authority (this url is shown in <span class='label label-default'>grey</span>). 
    A real system could handle this for the user by using a whitelist of trusted certifcate 
    locations, either stored within the system itself or provided by a trusted 3rd party. 
</p>

<script src="TinCanStatementViewer/scripts/jquery-1.6.3.min.js"></script>
<script src="TinCanStatementViewer/scripts/base64.js"></script>
<script src="TinCanJS/build/tincan-min.js"></script>
<script src="TinCanStatementViewer/scripts/TinCanQueryUtils.js"></script>
<script src="TinCanStatementViewer/scripts/TinCanViewer.js"></script>
<script src="TinCanViewerOverrides.js"></script>

<div id="searchBox" style="display: none;">
    <input type="hidden" id="version" value="<?php echo $CFG->version ?>" />
    <input type="hidden" id="agentProperty" value="mbox" />
    <input id="agentValue" type="hidden" value="">
    <input id="verb1" type="hidden" value="">
    <input id="activityId1" type="hidden" value="http://standard.openbadges.org/xapi/recipe/base/0">
    <input id="format" type="hidden" value="canonical">
    <input id="since1" type="hidden" value="">
    <input id="until1" type="hidden" value="">
    <input id="registration1" type="hidden" value="">
    <input id="relatedAgents" type="hidden">
    <input id="relatedActivities" type="checkbox" checked>
    <input id="attachments" type="checkbox" checked>

    <textarea readonly="true" id="TCAPIQueryText"></textarea>

</div>
<div id='theStatements'></div>
<div id='statementsLoading'>
    <img src="TinCanStatementViewer/img/loading.gif" alt="Loading">
</div>
<button id='showAllStatements' class="btn btn-info">More...</button>


<script>
//TODO: put this in a separate js file
    function Config() {
        "use strict";
    }
    Config.endpoint = "<?php echo $CFG->endpoint ?>";
    Config.authUser = "<?php echo $CFG->readonly_login ?>";
    Config.authPassword = "<?php echo $CFG->readonly_pass ?>";
    Config.actor = { "mbox":["<?php echo $userEmail; ?>"], "name":["<?php echo $userName ?>"] };

    $(document).ready(function() {
        TC_VIEWER = new TINCAN.Viewer();
        TC_VIEWER.pageInitialize();
        TC_VIEWER.searchStatements();
        $(".statement").each(function(index){
            console.log("statement");
            displayAttachments($(this));
        });

    });

    function displayAttachments(statementElement) {
        var statement = new TinCan.Statement(statementElement.next(".tc_rawdata").children("pre").text());
    }
</script>